### ISSUE TITLE
Define fast compose

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/idris-ct#18]
In a free smc, you give me two morphisms `f` `g` such that the codomain of `f` is a permutation of the domain of `g`. You also give me a list of binary swaps to turn one into the other. I will figure out for you a list of morphisms `h_1`, ..., `h_n` such that each `h_i` has the form `id tensor symmetry tensor id`, and such that the composition `f;h_1;..;h_n;g` makes sense. Said composition is what I will give you back.

**Comment by marcosh** [comment]
moved to https://github.com/statebox/idris-stbx-core/issues/37
