### ISSUE TITLE
Fast compose with same types

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/idris-ct#20]
Like #19 but now we allow repeated generators in the object. The users should be able to specify if they want the same generators to be swapped, and how. If they do not specify anything, then fastcompose should compose `f` and `g` without swapping the same object. This is analogous to "swapfree" symmetries in https://arxiv.org/abs/1904.12974 . 
I know this specifications suck a bit, but they are a starting point to make clear what is that we want to achieve conceptually :)

**Comment by marcosh** [comment]
moved to https://github.com/statebox/idris-stbx-core/issues/39
